### ISSUE TITLE
npm run watch not working

### ISSUE THREAD

**Issue by moshkito** [charleshacks/fivem-vue-tailwind-boilerplate#3]
PS D:\dev\fivem-vue-tailwind-boilerplate\nui> npm run watch

> fivem-vue-tailwind-boilerplate@0.0.0 watch
> mix watch

node:internal/errors:540
      throw error;
      ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received type number (0).
    at Socket.send (node:dgram:635:12)
    at Rcon._sendSocket (D:\dev\fivem-vue-tailwind-boilerplate\nui\node_modules\rcon\node-rcon.js:78:21)
    at Rcon.socketOnConnect (D:\dev\fivem-vue-tailwind-boilerplate\nui\node_modules\rcon\node-rcon.js:207:10)
    at Socket.<anonymous> (D:\dev\fivem-vue-tailwind-boilerplate\nui\node_modules\rcon\node-rcon.js:94:55)
    at Socket.emit (node:events:520:28)
    at startListening (node:dgram:182:10)
    at node:dgram:373:7
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_SOCKET_BAD_PORT'
}

Node.js v22.3.0

**Comment by Kxiox** [comment]
Did you fixed it?

**Comment by JensGryspeert** [comment]
You need to make a copy of the `.env.example` and renamed that copied file to `.env`. Try to rerun it now it shoud work.
